### ISSUE TITLE
it can‘t work for ES2.3.3

### ISSUE THREAD

**Issue by sevenma** [lucidfrontier45/ElasticsearchSink2#9]
please test it for ES2.3.3.

16/06/14 13:17:37 ERROR elasticsearch2.ElasticSearchSink: Failed to commit transaction. Transaction rolled back.
NoNodeAvailableException[None of the configured nodes are available: []]
        at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:280)
        at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:197)
        at org.elasticsearch.client.transport.support.TransportProxyClient.execute(TransportProxyClient.java:55)
        at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:272)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:347)
        at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:85)
        at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:59)
        at com.frontier45.flume.sink.elasticsearch2.client.ElasticSearchTransportClient.execute(ElasticSearchTransportClient.java:178)
        at com.frontier45.flume.sink.elasticsearch2.ElasticSearchSink.process(ElasticSearchSink.java:187)
        at org.apache.flume.sink.DefaultSinkProcessor.process(DefaultSinkProcessor.java:68)
        at org.apache.flume.SinkRunner$PollingRunner.run(SinkRunner.java:147)
        at java.lang.Thread.run(Thread.java:745)

this is my flume.conf:

`# Name the components on this agent
a1.sources = r1
a1.sinks = k1
a1.channels = c1
# Describe/configure the source

a1.sources.r1.type = org.apache.flume.chiwei.filemonitor.FileMonitorSource
a1.sources.r1.file=/usr/local/tomcat6/logs/catalina.out
a1.sources.r1.positionDir = /home/flume
# Describe the sink ES

a1.sinks.k1.type = com.frontier45.flume.sink.elasticsearch2.ElasticSearchSink
a1.sinks.k1.hostNames = 192.168.3.111:9300
a1.sinks.k1.indexName = basis_log_info
a1.sinks.k1.indexType = logs
a1.sinks.k1.clusterName = elastic-nginx
a1.sinks.k1.batchSize = 100
a1.sinks.k1.timeZone = Asia/Shanghai
a1.sinks.k1.ttl = 5d
a1.sinks.k1.serializer = com.frontier45.flume.sink.elasticsearch2.ElasticSearchDynamicSerializer
a1.sinks.k1.indexNameBuilder = com.frontier45.flume.sink.elasticsearch2.TimeBasedIndexNameBuilder
a1.sinks.k1.channel = c1
# Use a channel which buffers events in memory

a1.channels.c1.type = memory
a1.channels.c1.capacity = 100
a1.channels.c1.transactionCapacity = 80
# Bind the source and sink to the channel

a1.sources.r1.channels = c1
a1.sinks.k1.channel = c1`

**Comment by sevenma** [comment]
it works well for es2.0,
 but ES2.3.3,please check it if it works for es2.3.3

**Comment by lucidfrontier45** [comment]
@sevenma In which way did you build the jar?

``` bash
$ ./gradlew build # A
$ ./gradlew assembly # B
```

If A, you need to include es2.3 library jars in you CLASSPATH.
If B, you need to modify the build.gradle to use v2.3 as follows

``` gradle
compile 'org.elasticsearch:elasticsearch:2.3.0'
```

**Comment by lucidfrontier45** [comment]
see my comment https://github.com/lucidfrontier45/ElasticsearchSink2/pull/3#issuecomment-180726514

**Comment by sevenma** [comment]
thank you very very much, it works!!!
big hug~~~~~~~~~~~
